name: metrics

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contributions calendar
        uses: lowlighter/metrics@v3.34
        with:
          filename: contributions.svg
          token: ${{ secrets.METRICS_TOKEN || github.token }}
          user: ${{ github.repository_owner }}
          output_action: commit
          committer_branch: ${{ github.ref_name }}
          retries: 3
          retries_delay: 10
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_calendar: yes
          plugin_calendar_limit: 3
